### ISSUE TITLE
Change URL -> solr.quepid.com

### ISSUE THREAD

**Issue by softwaredoug** [o19s/bearded-wookie#2]
Instad of the EC2 URL, use a prettier URL

http://solr.quepid.com/solr/statedecoded/select?q=*:*

**Comment by epugh** [comment]
Damn open source projects..    Makes just anyone think they can come by and hassle you...    Patches welcome ;-)   

Seroiusly, thanks for the feedback, will add that change now.

**Comment by softwaredoug** [comment]
:-p

**Comment by epugh** [comment]
Done!
